### ISSUE TITLE
Dataset source

### ISSUE THREAD

**Issue by DHSeo11** [EJHyun/THOR#1]
I hope to look at the source of the data you provide.
Could you be able to tell the where to get the original data?

**Comment by EJHyun** [comment]
Thanks for your attention.
Here's links for the used datasets.

- ICEWS: https://dataverse.harvard.edu/dataverse/icews
- YAGO: https://www.mpi-inf.mpg.de/departments/databases-and-information-systems/research/yago-naga/yago/downloads/

You can have a look and get various versions of datasets.
I hope it helped.

Jay

**Comment by zhangzhaoxia** [comment]
Could you help me to see what the cause of this mistake is？

Traceback (most recent call last):
  File "E:\PycharmProjects\PycharmProjects\THOR-main\THOR-main\data\construct_graph.py", line 185, in <module>
    Train_Relation_Graph_.add_edges(Train_Line_Graph.ndata['relation_idx'][Train_Line_Graph.edges()[0]], Train_Line_Graph.ndata['relation_idx'][Train_Line_Graph.edges()[1]])
  File "D:\Anaconda3\lib\site-packages\dgl\heterograph.py", line 517, in add_edges
    F.cat([old_v, v], dim=0),
  File "D:\Anaconda3\lib\site-packages\dgl\backend\pytorch\tensor.py", line 174, in cat
    return th.cat(seq, dim=dim)
RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:76] data. DefaultCPUAllocator: not enough memory: you tried to allocate 1101843296 bytes.
